-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-05-23 16:11:47 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE authorship (
    song_song_id  INTEGER NOT NULL,
    singer_name   CHAR(20) NOT NULL
)
LOGGING;

ALTER TABLE authorship ADD CONSTRAINT authorship_pk PRIMARY KEY ( song_song_id,
                                                                  singer_name );

CREATE TABLE country (
    name CHAR(20) NOT NULL
)
LOGGING;

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( name );

CREATE TABLE genre (
    name CHAR(20) NOT NULL
)
LOGGING;

ALTER TABLE genre ADD CONSTRAINT genre_pk PRIMARY KEY ( name );

CREATE TABLE genreclassification (
    genre_name    CHAR(20) NOT NULL,
    song_song_id  INTEGER NOT NULL
)
LOGGING;

ALTER TABLE genreclassification ADD CONSTRAINT genreclassification_pk PRIMARY KEY ( genre_name,
                                                                                    song_song_id );

CREATE TABLE singer (
    name CHAR(20) NOT NULL
)
LOGGING;

ALTER TABLE singer ADD CONSTRAINT singer_pk PRIMARY KEY ( name );

CREATE TABLE song (
    title       CHAR(20) NOT NULL,
    popularity  INTEGER,
    length      INTEGER,
    song_id     INTEGER NOT NULL
)
LOGGING;

ALTER TABLE song ADD CONSTRAINT song_pk PRIMARY KEY ( song_id );


--  ERROR: UK name length exceeds maximum allowed length(30) 

ALTER TABLE song
    ADD CONSTRAINT song_title_popularity_length_un UNIQUE ( title,
                                                            popularity,
                                                            length );

CREATE TABLE tour (
    country_name  CHAR(20) NOT NULL,
    singer_name   CHAR(20) NOT NULL,
    "date"        DATE,
    tour_id       INTEGER NOT NULL
)
LOGGING;

ALTER TABLE tour ADD CONSTRAINT tour_pk PRIMARY KEY ( tour_id );

ALTER TABLE tour
    ADD CONSTRAINT tour__un UNIQUE ( country_name,
                                     "date",
                                     singer_name );

ALTER TABLE authorship
    ADD CONSTRAINT authorship_singer_fk FOREIGN KEY ( singer_name )
        REFERENCES singer ( name )
    NOT DEFERRABLE;

ALTER TABLE authorship
    ADD CONSTRAINT authorship_song_fk FOREIGN KEY ( song_song_id )
        REFERENCES song ( song_id )
    NOT DEFERRABLE;

ALTER TABLE genreclassification
    ADD CONSTRAINT genreclassification_genre_fk FOREIGN KEY ( genre_name )
        REFERENCES genre ( name )
    NOT DEFERRABLE;

ALTER TABLE genreclassification
    ADD CONSTRAINT genreclassification_song_fk FOREIGN KEY ( song_song_id )
        REFERENCES song ( song_id )
    NOT DEFERRABLE;

ALTER TABLE tour
    ADD CONSTRAINT tour_country_fk FOREIGN KEY ( country_name )
        REFERENCES country ( name )
    NOT DEFERRABLE;

ALTER TABLE tour
    ADD CONSTRAINT tour_singer_fk FOREIGN KEY ( singer_name )
        REFERENCES singer ( name )
    NOT DEFERRABLE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
